

volumes:
  jenkins-volume: {}
  jenkins-docker-certs: {}

services:
  
  jenkins:
    build:
      context: .
      dockerfile: jenkins/Dockerfile
    image: own_jenkins
    container_name: own_jenkins
    ports:
      - 8080:8080
      - 50000:50000
    restart: on-failure
    volumes:
      - jenkins-volume:/var/jenkins_home
      - jenkins-docker-certs:/certs/client:ro
    environment:
      - DOCKER_HOST=tcp://docker:2376
      - DOCKER_CERT_PATH=/certs/client
      - DOCKER_TLS_VERIFY=1