pipeline {
    agent any

    tools {
        // Instalar Maven desde las herramientas globales de Jenkins
        maven 'Maven 3.6.3'
        jdk 'jdk-11'
    }

    environment {
        ARTIFACTORY_URL = 'http://localhost:8081/artifactory'
        ARTIFACTORY_REPO = 'libs-release-local'
        ARTIFACTORY_CREDENTIALS = 'artifactory-credentials-id' // ID de las credenciales de Artifactory en Jenkins
    }

    stages {
        stage('Checkout') {
            steps {
                // Clonar el código fuente desde el repositorio
                git url: 'https://github.com/Wildesdar37/retail-off.git', branch: 'main'
            }
        }

        stage('Build and Test') {
            steps {
                // Cambiar al directorio retailoff antes de ejecutar comandos
                dir('retailoff') {
                    // Limpiar y construir el proyecto Maven
                    sh 'mvn clean package'

                    // Ejecutar los tests del proyecto Maven
                    sh 'mvn test'
                }
            }
        }

        stage('Deploy') {
            steps {
                dir('retailoff') {
                    // Desplegar la aplicación localmente (puedes ajustar este comando según tus necesidades)
                    sh 'cp target/*.jar /retailoff/target/'
                }
            }
        }

        stage('Publish to Artifactory') {
            steps {
                dir('retailoff') {
                    script {
                        def server = Artifactory.server('artifactory-server-id') // ID del servidor Artifactory en Jenkins
                        def rtMaven = Artifactory.newMavenBuild()
                        rtMaven.tool = 'Maven 3.6.3' // Nombre de la herramienta Maven configurada en Jenkins
                        rtMaven.deployer releaseRepo: "${ARTIFACTORY_REPO}", snapshotRepo: "${ARTIFACTORY_REPO}", server: server
                        rtMaven.resolver releaseRepo: "${ARTIFACTORY_REPO}", snapshotRepo: "${ARTIFACTORY_REPO}", server: server

                        rtMaven.run pom: 'pom.xml', goals: 'clean install'

                        server.publishBuildInfo(rtMaven.publishBuildInfo())
                    }
                }
            }
        }
    }

    post {
        success {
            echo 'Build and tests were successful!'
        }
        failure {
            echo 'Build or tests failed.'
        }
    }
}
