pipeline {
    agent any

    tools {
        // Instalar Maven desde las herramientas globales de Jenkins
        maven 'Maven 3.6.3'
        jdk 'jdk-11'
        jfrog 'jfrog-cli'
    }

    environment {
        ARTIFACTORY_REPO = 'retailoff-dev'
        ARTIFACTORY_CREDENTIALS = 'jfrog-artifactory-id' // ID de las credenciales de Artifactory en Jenkins
    }

    stages {
        stage('Checkout') {
            steps {
                // Clonar el código fuente desde el repositorio
                git url: 'https://github.com/Wildesdar37/retail-off.git', branch: 'main'
            }
        }

        stage('Test') {
            steps {
                // Cambiar al directorio retailoff antes de ejecutar comandos
                dir('retailoff') {
                    // Ejecutar los tests del proyecto Maven
                    sh 'mvn test'
                }
            }
        }
        stage('Build') {
            steps {
                // Cambiar al directorio retailoff antes de ejecutar comandos
                dir('retailoff') {
                    // Limpiar y construir el proyecto Maven
                    sh 'mvn clean package'
                }
            }
        }

        stage('Publish to Artifactory') {
            steps {
                dir('retailoff') {
                    script {
                        sh 'echo ' + 'Publish to Artifactory'
                    }
                }
            }
        }

        post {
            success {
                echo 'Build and tests were successful!'
            }
            failure {
                echo 'Build or tests failed.'
            }
        }
    }
}
